### PR TITLE
refactor: use resources for data objects

### PR DESCRIPTION
**Pull request by Midnighter**
* Use `importlib_resources` which makes the package `zip_safe`.
* Update the package infrastructure to use more modern capabilities.

### CODE REVIEW

**Review by KristianJensen — COMMENTED** [review]
Looks fine. What is the advantage of doing things this way?

**Comment by Midnighter** [comment]
No huge differences at all. Just felt like trying out some new Python packaging features. The main thing is the loading of the data files in way that it can be done inside a zip archive (aka a Python egg). This is not possible when using constructs like `with open(join(dirname(__file__), "data", "filename"))`.

The `pyproject.toml` officially declares that this package uses setuptools. Moving content from the `setup.py` makes it possible to quickly switch to [flit](https://pypi.python.org/pypi/flit) or other package build tools that don't even use `setup.py` in future. (I should define the entry point in `setup.cfg` as well.)

**Comment by KristianJensen** [comment]
Alright. Is it ready to merge?

**Comment by Midnighter** [comment]
Yep, all good!

**Pull request merged**
